export const LOADING = 'LOADING';
export const GET_REPOSITORY_LIST = 'GET_REPOSITORY_LIST';
export const GET_ISSUE_LIST = 'GET_ISSUE_LIST';
export const GET_PR_LIST = 'GET_PR_LIST';
export const CLEAR_PAGINATION = 'CLEAR_PAGINATION';
